"""initial schema

Revision ID: 829b777c2d7a
Revises: 
Create Date: 2026-07-04 18:44:14.120991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '829b777c2d7a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('external_code', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('unit_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('nora_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rag_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chroma_id', sa.String(length=100), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('source_table', sa.String(length=100), nullable=False),
    sa.Column('source_ref', sa.String(length=500), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chroma_id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.Enum('weekly', 'monthly', 'quarterly', 'executive', name='report_type', native_enum=False), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('ga4', 'gsc', 'gbp', 'paid_media', 'crm', name='source_type', native_enum=False), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processed', 'failed', name='upload_status', native_enum=False), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crm_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('external_lead_id', sa.String(length=100), nullable=False),
    sa.Column('lead_source_raw', sa.String(length=300), nullable=False),
    sa.Column('lead_source_normalized', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('lead', 'tour', 'application', 'lease', 'lost', name='lead_status', native_enum=False), nullable=False),
    sa.Column('first_contact_date', sa.Date(), nullable=False),
    sa.Column('tour_date', sa.Date(), nullable=True),
    sa.Column('application_date', sa.Date(), nullable=True),
    sa.Column('lease_signed_date', sa.Date(), nullable=True),
    sa.Column('move_in_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'external_lead_id', name='uq_lead_property_external')
    )
    with op.batch_alter_table('crm_leads', schema=None) as batch_op:
        batch_op.create_index('ix_lead_property_contact', ['property_id', 'first_contact_date'], unique=False)
        batch_op.create_index('ix_lead_property_lease', ['property_id', 'lease_signed_date'], unique=False)

    op.create_table('ga4_sessions_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('session_source', sa.String(length=300), nullable=False),
    sa.Column('session_medium', sa.String(length=100), nullable=False),
    sa.Column('session_campaign', sa.String(length=300), nullable=True),
    sa.Column('landing_page', sa.String(length=1000), nullable=True),
    sa.Column('sessions', sa.Integer(), nullable=False),
    sa.Column('engaged_sessions', sa.Integer(), nullable=False),
    sa.Column('total_users', sa.Integer(), nullable=False),
    sa.Column('key_events', sa.Integer(), nullable=False),
    sa.Column('is_ai_referral', sa.Boolean(), nullable=False),
    sa.Column('ai_platform', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ga4_sessions_daily', schema=None) as batch_op:
        batch_op.create_index('ix_ga4_ai_date', ['is_ai_referral', 'date'], unique=False)
        batch_op.create_index('ix_ga4_property_date', ['property_id', 'date'], unique=False)

    op.create_table('gbp_metrics_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('search_impressions', sa.Integer(), nullable=False),
    sa.Column('maps_impressions', sa.Integer(), nullable=False),
    sa.Column('website_clicks', sa.Integer(), nullable=False),
    sa.Column('calls', sa.Integer(), nullable=False),
    sa.Column('direction_requests', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'date', name='uq_gbp_property_date')
    )
    op.create_table('gsc_performance_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('query', sa.String(length=500), nullable=True),
    sa.Column('page', sa.String(length=1000), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=False),
    sa.Column('position', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gsc_performance_daily', schema=None) as batch_op:
        batch_op.create_index('ix_gsc_property_date', ['property_id', 'date'], unique=False)

    op.create_table('nora_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='message_role', native_enum=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=True),
    sa.Column('gate_passed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['nora_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paid_media_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('campaign_name', sa.String(length=300), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('spend', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('conversions', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paid_media_daily', schema=None) as batch_op:
        batch_op.create_index('ix_paid_property_date', ['property_id', 'date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paid_media_daily', schema=None) as batch_op:
        batch_op.drop_index('ix_paid_property_date')

    op.drop_table('paid_media_daily')
    op.drop_table('nora_messages')
    with op.batch_alter_table('gsc_performance_daily', schema=None) as batch_op:
        batch_op.drop_index('ix_gsc_property_date')

    op.drop_table('gsc_performance_daily')
    op.drop_table('gbp_metrics_daily')
    with op.batch_alter_table('ga4_sessions_daily', schema=None) as batch_op:
        batch_op.drop_index('ix_ga4_property_date')
        batch_op.drop_index('ix_ga4_ai_date')

    op.drop_table('ga4_sessions_daily')
    with op.batch_alter_table('crm_leads', schema=None) as batch_op:
        batch_op.drop_index('ix_lead_property_lease')
        batch_op.drop_index('ix_lead_property_contact')

    op.drop_table('crm_leads')
    op.drop_table('uploads')
    op.drop_table('reports')
    op.drop_table('rag_chunks')
    op.drop_table('nora_conversations')
    op.drop_table('properties')
    # ### end Alembic commands ###
